# Generated by Django 4.0.2 on 2022-04-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diy', '0002_alter_website_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
