# Generated by Django 4.0.2 on 2022-04-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diy', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='webSite2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htmlString', models.TextField()),
                ('companyName', models.CharField(default='No name', max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='website',
            name='images',
        ),
    ]
