# Generated by Django 4.0.2 on 2022-05-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diy', '0005_website3'),
    ]

    operations = [
        migrations.CreateModel(
            name='webSite4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htmlString', models.TextField()),
                ('companyName', models.CharField(default='No name', max_length=60)),
            ],
        ),
    ]
